### ISSUE TITLE
情報ページでのバージョン表記が変

### ISSUE THREAD

**Issue by b2ox** [kurema/BookViewerApp#1]
InfoPageViewModel.csでVersionTextがMajor. Minor. Revision. Revisionになってます。
3つ目はBuildではないでしょうか。

>  public string VersionText => string.Format("{0}.{1}.{2}.{3}",VersionInfo.Major,VersionInfo.Minor,VersionInfo.Revision,VersionInfo.Revision);

**Comment by kurema** [comment]
確かにおかしいですね。
表示が変なのはアセンブリバージョンでも参照しているんだろうなと思って後回しにしていましたが、単純なミスでした。
修正してその他の機能拡張を含めてストアに提出したので数日すれば配信されると思います。

**Comment by kurema** [comment]
修正したのでクローズさせていただきます。
