### ISSUE TITLE
BookFixed2Viewer.xaml.cs の OnNavigatedTo に無駄なコードがある

### ISSUE THREAD

**Issue by b2ox** [kurema/BookViewerApp#2]
109行目 `if (e.Parameter == null) { }` はnullチェックしてるけど110行目にelseがないし無意味。

143行目は最後に144行目と同じコードがあり、 `currentView.BackRequested += CurrentView_BackRequested;` が2回実行されることになっている。

**Comment by kurema** [comment]
修正しました。
同様のバグは他に二カ所ありました。
関連した修正も多少行いました。

問題は軽微とは言えませんが、ストアでの更新は今後機能追加などをした時に行います。
クローズはその際にする事にします。

**Comment by kurema** [comment]
SharpCompressの更新と合わせてストアでも更新したのでクローズしました。
