### ISSUE TITLE
[Feature request] Folder view for bookshelf

### ISSUE THREAD

**Issue by TechTrooper** [kurema/BookViewerApp#3]
Hello,

I tried your app, but I couldn't set the bookshelf to show only my folders. 

All of my files are in folders such as: 
Berserk
Great Teacher Onizuka

But in your app all the files are shown in same view (bookshelf). 
My collection is very big and navigating through all the files is frustrating.

I hope you can implement library folder view such as in apps like 
**Cover - Comic Reader** or **Comicrack for Windows**

**Comment by kurema** [comment]
Thank you for your kind suggestion.

I know library function of this app requires lots of improvement.
But basic design of this app is somewhat obsolete.
It's much faster to rewrite whole than to improve current library function.
So no big improvement will be done for this.

I do have a plan to rewrite but it will take some time at least.
So don't expect too much.
It will be notified in app if it's done.

**Comment by kurema** [comment]
Folder view function is now in [BookViewerApp3](https://github.com/kurema/BookViewerApp3).
It's prerelease but issue is closed now.
